### ISSUE TITLE
Use JQuery in ExtJs 4.2.x

### ISSUE THREAD

**Issue by pontiyaraja** [loiane/extjs4-crud-mvc-screencast#1]
Hi, 
     I am new to extjs. I like to use jquery in extjs. Can we use jquery in ExtJs view file.

**Comment by loiane** [comment]
Yes, pls take a look at this example:
https://github.com/loiane/curso-extjs4/tree/master/aula04

_Loiane Groner_
English Blog: http://loianegroner.co http://loianegroner.comm
Pt-br Blog: http://www.loiane.com

**Comment by pontiyaraja** [comment]
Thank you.
